Update to handle more cases

diff --git a/.github/workflows/Release.yaml b/.github/workflows/Release.yaml
--- a/.github/workflows/Release.yaml
+++ b/.github/workflows/Release.yaml
@@ -46,9 +46,21 @@ jobs:
         env:
           NUGET_API_KEY: ${{ secrets.QUANTORI_NUGET_API_KEY }}
         run: |
-          if dotnet nuget push ./Behavioral.Automation.${{ env.VER }}.nupkg -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate 2>&1 | tee /dev/stderr | grep -q "403"; then
+          exit_code=0
+          output=$(dotnet nuget push ./Behavioral.Automation.${{ env.VER }}.nupkg -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate 2>&1) || {
+            echo "An error occurred while running the dotnet nuget push command."
+            exit_code=1
+          }
+
+          echo "$output"
+          echo "Exit Code: $exit_code"
+
+          if echo "$output" | grep -q "403"; then
             echo "Error: NuGet API key is invalid or expired. Please contact Quantori support to renew the key. For more details, refer to the Quantori BDD Confluence page called 'Renew NuGet API key'."
-          exit 1
+            exit 1
+          elif [ $exit_code -ne 0 ]; then
+            echo "Error: dotnet nuget push failed. Check the logs for more details."
+            exit 1
           else
             echo "Package successfully published to NuGet.org."
           fi
